apiVersion: v1
kind: Service
metadata:
  name: test-web-api-application
  labels:
    app: test-web-api-application
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: test-web-api-application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-web-api-application
  labels:
    app: test-web-api-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-web-api-application
  template:
    metadata:
      labels:
        app: test-web-api-application
    spec:
      containers:
        - name: test-web-api-application
          image: codefuller/test-web-api-application:1
          ports:
            - containerPort: 80
          env:
          - name: APPINSIGHTS_INSTRUMENTATIONKEY
            value: "<Fill Me>"
          - name: APPLICATIONINSIGHTS_CONNECTION_STRING
            value: "<Fill Me>"
