apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Service
metadata:
  name: test-web-api-application
  labels:
    app: test-web-api-application
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: test-web-api-application
---
# https://github.com/Microsoft/ApplicationInsights-Kubernetes/blob/develop/examples/BasicUsage_clr21_RBAC/README.MD#setup-the-default-service-account-for-rbac-enabled-cluster
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: appinsights-k8s-property-reader
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["pods", "nodes", "replicasets", "deployments"]
  verbs: ["get", "watch", "list"]
---
# actual binding to the role
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appinsights-k8s-property-reader-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: test
roleRef:
  kind: ClusterRole
  name: appinsights-k8s-property-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: test-application-insights
data:
  testInstrumentationKey: <fill me>
  testConnectionString: <fill me>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-web-api-application
  labels:
    app: test-web-api-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-web-api-application
  template:
    metadata:
      labels:
        app: test-web-api-application
    spec:
      containers:
        - name: test-web-api-application
          image: codefuller/test-web-api-application:v3
          ports:
            - containerPort: 80
          env:
          - name: APPINSIGHTS_INSTRUMENTATIONKEY
            valueFrom:
              secretKeyRef:
                name: test-application-insights
                key: testInstrumentationKey
          - name: APPLICATIONINSIGHTS_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: test-application-insights
                key: testConnectionString
